### ISSUE TITLE
alt and title attributt mangler på bilder

### ISSUE THREAD

**Issue by steinmb** [steinmb/dhs_migrate#10]
Disse blir ikke migrert over fra D6
### Ekempel node

D6: http://www.dhs.museum.no/hagekveld-p%C3%A5-museet
D7: http://dhs.smbjorklund.no/hagekveld-p%C3%A5-museet

**Comment by steinmb** [comment]
@hewiro Commit e3fb516 drar disse inn under import. 

Om de mangler skriver den inn en standardtekst: (c) De Heibergske Samlinger-Sogn Folkemuseum. De blir ikke med når bildet vises men det har ikke noe med selve importeringen å gjøre. Trolig må dette fikses i template når vi går løs på den. Har likevell opprettet en annen sak som tracker denne #10

**Comment by hewiro** [comment]
Denne artikkelen skal uansett slettes.
