### ISSUE TITLE
Mangler taxonomy term på engelsk innhold

### ISSUE THREAD

**Issue by steinmb** [steinmb/dhs_migrate#12]
Hei @hewiro 
Du får rette meg om jeg tar feil, men det ser ut som at engelske artikkler ikke har noen taksonomi termer knyttet til seg (topics). Du kan hjelpe meg å sjekke dette

**Comment by hewiro** [comment]
Du her trolig rett. Den engelske siden er blitt sett langt tilbake og må gjøres bedre fremover. Skal gå gjennom sidene og se hva jeg kan rette opp...

**Comment by hewiro** [comment]
Har lagt til taxonomi på alle de sidene som er publisert på engelsk (tror jeg) men ser at det ligger en del gamle sider som ikke lenger er publisert. Skal se gjennom disse og. Kan kanskje slette alle disse...

**Comment by steinmb** [comment]
Jeg snakker om migrert innhold i Drupal 7 (http://dhs.smbjorklund.no/), ikke hva som finnes i Drupal 6 versjonen

**Comment by steinmb** [comment]
Ah, ser noe vi bør endre på først. Bruker entity reference til å peke på de forskjellige taggene, det er ikke en god ide. Skal endre disse til taxonomy ref. feil. Må rive ned det feltet vi har og lage et nytt og endre migrasjon. Hører dog værre ut enn hva det egentlig er.

**Comment by steinmb** [comment]
Dette er fra Drupal 6. Vi har feil og en svakhet i artikkler der. Dette er en node som jeg opprettet som ny på engelsk. Legg merke til at språket blir feilaktig satt til Norsk.

![engelsk_test___de_heibergske_samlinger-sogn_folkemuseum](https://cloud.githubusercontent.com/assets/683617/8191591/2feae898-1469-11e5-8974-718328d03654.png)

Nest gang noden blir redigert laster den ikke de taxonomi termene som ikke har korrekt språk og tagg linjen er tom. Lager man derimot nye tagger nå havner disse i riktig språk og riktig vokabular. Den engelske som ble opprett i det norske vokabular blir feilaktig liggende igjen, ubrukt.

**Comment by steinmb** [comment]
Noe mere komplisert dette. Har lagt til denne 9c41329 som passer på at de får språk på vei inn. Mangler språk blir de satt til "und" som er anbefalt oppførsel når disse ikke er definert til de to språkene vi har.

### Etter endring i kode

![tagger___de_heibergske_samlinger-sogn_folkemuseum](https://cloud.githubusercontent.com/assets/683617/8203103/c00e108c-14df-11e5-968a-7d52e914164d.png)

**Comment by hewiro** [comment]
Mye til og fra i dag. Mange turister.
Dumt spørsmål kanskje, men er det bare fotoalbumene som er kommet over i D7? Mangler Admin verktøyet så jeg kommer ikke inn i innholdoversikten selv om jeg har logget inn...

**Comment by steinmb** [comment]
Fixet i 0f93531 Resten må eventuelt gjøre direkte i D7/8.
