### ISSUE TITLE
Automagisk kopiere database og filer fra produksjon til D7

### ISSUE THREAD

**Issue by steinmb** [steinmb/dhs_migrate#6]
Siden vi importerer fra produksjon (Drupal 6) hadde det vært greit å kunne nå serveren og fått siste kopi av database og filene (vedlegg og bilder) over.
## Foreslått løsning:

Skript som kjører rsync og henter siste databasekopi,  det tas en i døgnet for DHS, og hele filområdet (public://). Dette bør fungere og kjøre både på sentral server og lokal utviklingsmaskiner.

**Comment by hewiro** [comment]
Trengs noe tilgang fra Fjordane It? Eller fixer du dette selv?

**Comment by steinmb** [comment]
Tror jeg har det jeg trenger. Det er om at jeg ikke har mistet noen tilganger siden sist jeg var logget inn på serverne via ssh.

**Comment by hewiro** [comment]
Håper det. De byttet server for et par uker siden og flyttet alt og alle til et nytt anlegg langt inne i Jostedalen. 
Har ikke merket noen forskjell, så det er nok som før...

**Comment by steinmb** [comment]
Dette fungerer. Sync av filer og derpåfølgende migrering av Drupal 6 data.
